-- Auto-generated dummy data for valgfagsfordelingdb (v4, unique priorities per student)
USE valgfagsfordelingdb;

START TRANSACTION;

-- ===================== TEACHERS =====================
INSERT INTO teacher (teacher_full_name) VALUES ('Underviser_A');
INSERT INTO teacher (teacher_full_name) VALUES ('Underviser_B');
INSERT INTO teacher (teacher_full_name) VALUES ('Underviser_C');
INSERT INTO teacher (teacher_full_name) VALUES ('Underviser_D');
INSERT INTO teacher (teacher_full_name) VALUES ('Underviser_E');
INSERT INTO teacher (teacher_full_name) VALUES ('Underviser_F');

-- ===================== COURSES =====================
INSERT INTO course (course_name, description, participants_count, max_participants, min_participants, semester, teacher_id) VALUES ('Full Stack Node.js', 'Udvikling af webapplikationer med Node.js, Express og databaser.', 0, 35, 8, 'forår2026', 1);
INSERT INTO course (course_name, description, participants_count, max_participants, min_participants, semester, teacher_id) VALUES ('IT-sikkerhed', 'Grundlæggende principper, trusselsmodeller, sikkerhed i praksis.', 0, 35, 8, 'forår2026', 2);
INSERT INTO course (course_name, description, participants_count, max_participants, min_participants, semester, teacher_id) VALUES ('AI Agenter', 'Introduktion til kunstig intelligens og agentbaserede systemer.', 0, 35, 8, 'forår2026', 6);
INSERT INTO course (course_name, description, participants_count, max_participants, min_participants, semester, teacher_id) VALUES ('Datastrukturer og algoritmer', 'Effektive datastrukturer og algoritmiske teknikker.', 0, 35, 8, 'forår2026', 3);
INSERT INTO course (course_name, description, participants_count, max_participants, min_participants, semester, teacher_id) VALUES ('IT Drift', 'Opsætning og vedligeholdelse af IT-infrastruktur.', 0, 35, 8, 'forår2026', 4);
INSERT INTO course (course_name, description, participants_count, max_participants, min_participants, semester, teacher_id) VALUES ('Low Level C', 'Programmering tæt på maskinen i C.', 0, 35, 8, 'forår2026', 3);
INSERT INTO course (course_name, description, participants_count, max_participants, min_participants, semester, teacher_id) VALUES ('Intro til Python', 'Introduktion til programmering i Python.', 0, 35, 8, 'forår2026', 5);
INSERT INTO course (course_name, description, participants_count, max_participants, min_participants, semester, teacher_id) VALUES ('DevOps', 'Automatisering og deployment i moderne IT-miljøer.', 0, 35, 8, 'forår2026', 1);

-- ===================== STUDENTS =====================
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_001', 'elev001@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_002', 'elev002@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_003', 'elev003@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_004', 'elev004@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_005', 'elev005@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_006', 'elev006@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_007', 'elev007@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_008', 'elev008@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_009', 'elev009@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_010', 'elev010@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_011', 'elev011@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_012', 'elev012@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_013', 'elev013@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_014', 'elev014@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_015', 'elev015@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_016', 'elev016@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_017', 'elev017@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_018', 'elev018@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_019', 'elev019@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_020', 'elev020@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_021', 'elev021@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_022', 'elev022@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_023', 'elev023@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_024', 'elev024@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_025', 'elev025@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_026', 'elev026@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_027', 'elev027@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_028', 'elev028@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_029', 'elev029@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_030', 'elev030@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_031', 'elev031@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_032', 'elev032@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_033', 'elev033@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_034', 'elev034@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_035', 'elev035@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_036', 'elev036@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_037', 'elev037@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_038', 'elev038@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_039', 'elev039@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_040', 'elev040@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_041', 'elev041@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_042', 'elev042@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_043', 'elev043@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_044', 'elev044@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_045', 'elev045@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_046', 'elev046@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_047', 'elev047@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_048', 'elev048@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_049', 'elev049@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_050', 'elev050@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_051', 'elev051@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_052', 'elev052@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_053', 'elev053@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_054', 'elev054@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_055', 'elev055@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_056', 'elev056@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_057', 'elev057@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_058', 'elev058@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_059', 'elev059@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_060', 'elev060@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_061', 'elev061@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_062', 'elev062@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_063', 'elev063@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_064', 'elev064@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_065', 'elev065@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_066', 'elev066@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_067', 'elev067@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_068', 'elev068@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_069', 'elev069@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_070', 'elev070@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_071', 'elev071@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_072', 'elev072@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_073', 'elev073@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_074', 'elev074@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_075', 'elev075@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_076', 'elev076@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_077', 'elev077@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_078', 'elev078@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_079', 'elev079@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_080', 'elev080@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_081', 'elev081@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_082', 'elev082@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_083', 'elev083@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_084', 'elev084@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_085', 'elev085@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_086', 'elev086@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_087', 'elev087@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_088', 'elev088@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_089', 'elev089@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_090', 'elev090@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_091', 'elev091@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_092', 'elev092@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_093', 'elev093@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_094', 'elev094@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_095', 'elev095@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_096', 'elev096@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_097', 'elev097@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_098', 'elev098@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_099', 'elev099@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_100', 'elev100@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_101', 'elev101@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_102', 'elev102@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_103', 'elev103@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_104', 'elev104@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_105', 'elev105@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_106', 'elev106@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_107', 'elev107@skole.dk', 0);
INSERT INTO student (full_name, email, handling_count) VALUES ('Elev_108', 'elev108@skole.dk', 0);


-- ===================== PRIORITIES =====================
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 1, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 1, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 1, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 1, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 1, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 2, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 2, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 2, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 2, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 2, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 98, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 98, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 98, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 98, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 98, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 4, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 4, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 4, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 4, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 4, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 5, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 5, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 5, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 5, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 5, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 6, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 6, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 6, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 6, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 6, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 7, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 7, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 7, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 7, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 7, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 8, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 8, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 8, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 8, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 8, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 9, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 9, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 9, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 9, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 9, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 10, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 10, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 10, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 10, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 10, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 11, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 11, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 11, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 11, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 11, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 12, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 12, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 12, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 12, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 12, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 13, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 13, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 13, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 13, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 13, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 14, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 14, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 14, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 14, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 14, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 15, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 15, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 15, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 15, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 15, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 16, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 16, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 16, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 16, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 16, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 17, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 17, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 17, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 17, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 17, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 18, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 18, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 18, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 18, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 18, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 19, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 19, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 19, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 19, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 19, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 20, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 20, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 20, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 20, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 20, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 21, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 21, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 21, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 21, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 21, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 22, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 22, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 22, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 22, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 22, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 23, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 23, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 23, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 23, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 23, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 24, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 24, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 24, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 24, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 24, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 25, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 25, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 25, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 25, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 25, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 26, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 26, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 26, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 26, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 26, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 27, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 27, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 27, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 27, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 27, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 28, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 28, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 28, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 28, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 28, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 29, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 29, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 29, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 29, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 29, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 30, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 30, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 30, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 30, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 30, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 31, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 31, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 31, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 31, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 31, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 32, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 32, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 32, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 32, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 32, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 33, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 33, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 33, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 33, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 33, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 34, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 34, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 34, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 34, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 34, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 35, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 35, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 35, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 35, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 35, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 36, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 36, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 36, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 36, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 36, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 37, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 37, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 37, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 37, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 37, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 38, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 38, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 38, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 38, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 38, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 39, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 39, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 39, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 39, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 39, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 40, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 40, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 40, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 40, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 40, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 41, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 41, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 41, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 41, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 41, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 42, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 42, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 42, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 42, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 42, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 43, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 43, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 43, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 43, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 43, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 44, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 44, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 44, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 44, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 44, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 45, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 45, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 45, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 45, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 45, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 46, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 46, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 46, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 46, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 46, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 47, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 47, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 47, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 47, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 47, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 48, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 48, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 48, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 48, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 48, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 49, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 49, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 49, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 49, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 49, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 50, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 50, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 50, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 50, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 50, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 51, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 51, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 51, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 51, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 51, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 52, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 52, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 52, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 52, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 52, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 53, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 53, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 53, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 53, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 53, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 54, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 54, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 54, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 54, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 54, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 55, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 55, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 55, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 55, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 55, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 56, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 56, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 56, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 56, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 56, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 57, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 57, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 57, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 57, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 57, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 58, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 58, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 58, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 58, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 58, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 59, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 59, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 59, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 59, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 59, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 60, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 60, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 60, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 60, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 60, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 61, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 61, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 61, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 61, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 61, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 62, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 62, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 62, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 62, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 62, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 63, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 63, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 63, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 63, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 63, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 64, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 64, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 64, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 64, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 64, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 65, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 65, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 65, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 65, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 65, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 66, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 66, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 66, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 66, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 66, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 67, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 67, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 67, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 67, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 67, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 68, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 68, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 68, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 68, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 68, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 69, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 69, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 69, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 69, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 69, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 70, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 70, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 70, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 70, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 70, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 71, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 71, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 71, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 71, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 71, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 102, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 102, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 102, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 102, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 102, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 73, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 73, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 73, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 73, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 73, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 74, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 74, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 74, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 74, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 74, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 75, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 75, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 75, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 75, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 75, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 76, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 76, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 76, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 76, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 76, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 77, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 77, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 77, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 77, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 77, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 78, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 78, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 78, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 78, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 78, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 79, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 79, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 79, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 79, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 79, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 80, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 80, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 80, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 80, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 80, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 81, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 81, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 81, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 81, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 81, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 82, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 82, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 82, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 82, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 82, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 83, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 83, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 83, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 83, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 83, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 84, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 84, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 84, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 84, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 84, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 85, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 85, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 85, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 85, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 85, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 86, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 86, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 86, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 86, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 86, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 87, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 87, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 87, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 87, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 87, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 88, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 88, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 88, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 88, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 88, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 89, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 89, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 89, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 89, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 89, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 90, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 90, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 90, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 90, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 90, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 91, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 91, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 91, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 91, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 91, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 92, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 92, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 92, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 92, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 92, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 93, 2);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 93, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 93, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 93, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 93, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 94, 1);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 94, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 94, 6);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 94, 7);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 94, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (1, 0, 95, 8);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (2, 0, 95, 4);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (3, 0, 95, 5);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (4, 0, 95, 3);
INSERT INTO priority (priority_number, fulfilled, student_id, course_id) VALUES (5, 0, 95, 7);

COMMIT;